name: Notify Release Job

on:
  workflow_call:
    inputs:
      TYPE:
        description: 'Type of release Notification, e.g. Tag, Github, NPM, Docker, etc'
        type: string
        required: true
      RELEASE_VERSION:
        description: 'Release information, e.g. v{{version}}'
        type: string
        required: true
      RELEASE_URL:
        description: 'Release URL, e.g. https://github.com/{{org}}/{{repository}}/releases/tag/{{version}}'
        type: string
        required: true
      JOB_STATUS:
        description: 'The current status of the job. Possible values are success, failed, skipped, or cancelled.'
        type: string
        required: true
      JOB_URL:
        description: 'URL for Job'
        type: string
        required: false
        default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      PROJECT:
        description: 'Name of project'
        type: string
        required: false
        default: ${{ github.repository }}
      CHANGE_URL:
        description: 'URL for commit or pr'
        type: string
        required: false
        default: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
      CUSTOM_MSG:
        description: 'Optional custom message'
        type: string
        required: false
      ## TODO: Consider including the release changes in the notification?
      # RELEASE_CHANGE_ARTEFACT:
      #   description: 'Uploaded Artefact containing the Changelog diff between releases'
      #   type: string
      #   required: true
      # RELEASE_CHANGE_FILENAME:
      #   description: 'Name of file referenced from Uploaded Artefact containing the Changelog diff between releases'
      #   type: string
      #   required: true
    secrets:
      SLACK_BOT_TOKEN:
        description: 'Slack Bot Token'
        required: true
      SLACK_CHANEL:
        description: 'Slack channel'
        required: true

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    ## TODO: Consider including the release changes in the notification?
    # - uses: actions/download-artifact@v4
    #   with:
    #     name: ${{ inputs.RELEASE_CHANGE_ARTEFACT }}
    #     path: /tmp/
    # - name: Release info
    #   run: |
    #     echo "RELEASE_CHANGE_ARTEFACT/RELEASE_CHANGE_FILENAME contents:"
    #     cat /tmp/${{ inputs.RELEASE_CHANGE_FILENAME }}
    #     echo "------------------------------"
    #     echo "RELEASE_TAG=${{ inputs.RELEASE_VERSION }}"
    # - name: Fetch changelog
    #   run: |
    #     echo 'RELEASE_CHANGES<<EOF' >> $GITHUB_ENV
    #     cat /tmp/${{ inputs.RELEASE_CHANGE_FILENAME }} >> $GITHUB_ENV
    #     echo 'EOF' >> $GITHUB_ENV
    - name: Release info
      run: |
        echo "RELEASE_VERSION=${{ inputs.RELEASE_VERSION }}"
    - name: if JOB_STATUS == 'success'
      if: ${{ inputs.JOB_STATUS == 'success' }}
      run: echo 'COLOR=#5abc54' >> $GITHUB_ENV
    - name: if JOB_STATUS != 'success'
      if: ${{ inputs.JOB_STATUS != 'success' }}
      run: echo 'COLOR=#FF3333' >> $GITHUB_ENV
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ secrets.SLACK_CHANEL }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "attachments": [
              {
                "color": "${{ env.COLOR }}",
                "blocks": [
                  {
                      "type": "header",
                      "text": {
                          "type": "plain_text",
                          "text": "${{ inputs.PROJECT }}",
                          "emoji": true
                      }
                  },
                  {
                      "type": "divider"
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "Type: `${{ inputs.TYPE }}`\nTag: `${{ inputs.RELEASE_VERSION }}`"
                      }
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "${{ inputs.RELEASE_URL }}"
                      }
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "Status: `${{ inputs.JOB_STATUS }}` @ ${{ inputs.CHANGE_URL }}"
                      },
                      "accessory": {
                          "type": "button",
                          "text": {
                              "type": "plain_text",
                              "text": "View",
                              "emoji": true
                          },
                          "value": "visit_job_btn",
                          "url": "${{ inputs.JOB_URL }}",
                          "action_id": "button-action"
                      }
                  },
                  {
                      "type": "divider"
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "${{ inputs.CUSTOM_MSG }} "
                      }
                  }
                ]
              }
            ]
          }
